name: 'Support Request'

on:
  issues:
    types: [labeled, unlabeled, reopened]

jobs:
  support:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v2
        with:
          github-token: ${{ github.token }}
          support-label: 'support'
          issue-comment: >
            :wave: @{issue-author}, we use the issue tracker exclusively
            for bug reports and feature requests. However, this issue appears
            to be a support request. Please use our support channels
            to get help with Varken!

            - [Discord](https://discord.gg/VjZ6qSM)
            - [Discord Quick Access](http://cyborg.decreator.dev/channels/518970285773422592/530424560504537105/)
          close-issue: true
          lock-issue: false
          issue-lock-reason: 'off-topic'
